name: 'Image Shrinker'
description: 'Recursively shrink images to a given maximum width/height while maintaining aspect ratio.'
author: 'TheGroundZero'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  subdir:
    description: Relative path starting from / in repo
    required: false
    default: ""
  maxwidth:
    description: Maximum width of the image
    required: false
    default: "1920"
  maxheight:
    description: Maximum height of the image
    required: false
    default: "1080"
branding:
  icon: 'crop'
  color: 'orange'